// import Head from "next/head";
// import styles from "styles/Home.module.css";
// import Web3 from "web3";
// import { useRouter } from "next/router";
// import TVD from "components/StableCoinAutoCompound/TVD";

// import {
//   Text,
//   Grid,
//   Container,
//   Box,
//   GridItem,
//   Image,
//   Spinner,
//   Center,
//   IconButton,
//   ButtonGroup,
//   Divider,
// } from "@chakra-ui/react";
// import { useEffect, useState } from "react";
// import { FaCalculator } from "react-icons/fa";
// import CountUp from "react-countup";
// import Portfolio from "../../components/StableCoinAutoCompound/Portfolio";

// import { Panel } from "../../components/StableCoinAutoCompound/Panel";

// const StableCoinAutoCompound = () => {
//   const info = {
//     poolName: "",
//     label: "",
//     description: "",
//     tvd: 100,
//     apy: 100,
//   };

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Mimic Finance | Multi Farming Yields Aggerator System</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Container maxW="container.xl" mt={10}>
//         <>
//           <Grid templateColumns="repeat(10, 1fr)" gap={6}>
//             <GridItem colSpan={1}>
//               <Box>
//                 <Image
//                   src={"/assets/images/pools/stable-coin.png"}
//                   alt="stable-coin-pool-auto"
//                   width={200}
//                 />
//               </Box>
//             </GridItem>
//             <GridItem colSpan={7}>
//               <Text fontSize="4xl">
//                 <b>Auto-Compound: Stable Coin</b>
//               </Text>
//             </GridItem>
//             <GridItem colSpan={2} style={{ textAlign: "right" }}>
//               <ButtonGroup variant="ghost" color="gray.600">
//                 <IconButton
//                   aria-label="Calculator"
//                   icon={<FaCalculator fontSize="15px" />}
//                 />
//               </ButtonGroup>
//               &nbsp; APY
//               <Text fontSize="4xl">50 %</Text>
//             </GridItem>
//           </Grid>

//           <Grid templateColumns="repeat(10, 1fr)" gap={10} mt={7}>
//             <GridItem colSpan={6}>
//               <Text fontSize="xl">
//                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A stablecoin is
//                 a class of cryptocurrencies that attempt to offer price
//                 stability and are backed by a reserve asset. Stablecoins have
//                 gained traction as they attempt to offer the best of both
//                 worlds—the instant processing and security or privacy of
//                 payments of cryptocurrencies, and the volatility-free stable
//                 valuations of fiat currencies.
//               </Text>

//               <Box mt={10}>
//                 <Text fontSize="xl">
//                   <b>Total Value Deposited</b>
//                 </Text>
//                 {/* <TVD></TVD> (to do fix) */}
//               </Box>
//             </GridItem>
//             <GridItem colSpan={4}>
//               <Panel info={info} />
//               {/* <Portfolio></Portfolio> */}
//             </GridItem>
//           </Grid>
//         </>
//       </Container>
//     </div>
//   );
// };

// export default StableCoinAutoCompound;

import { useEffect, useState, useCallback } from "react";

import styles from "styles/Home.module.css";
import Head from "next/head";
import OpenAutoCompoundPool from "constants/OpenAutoCompoundPool.json";
import { PoolContextProvider } from "contexts/PoolContext";
import { Panel } from "components/StableCoinAutoCompound/Panel";
import { useERC20Utils } from "hooks/useContracts";
import { useRouter } from "next/router";

import {
  Text,
  Grid,
  Container,
  Box,
  GridItem,
  Image,
  IconButton,
  ButtonGroup,
} from "@chakra-ui/react";

import { FaCalculator } from "react-icons/fa";
import TVD from "components/StableCoinPool/TVD";

const StableCoinAutoCompound = () => {
  const router = useRouter();
  const { address } = router.query;
  const ERC20Utils = useERC20Utils();
  const [symbol, setSymbol] = useState();

  // force load
  const info = OpenAutoCompoundPool[0]

  const getImage = (address) => {
    return `https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/${address}/logo.png`;
  };

  const getSymbol = useCallback(async () => {
    try {
      const _symbol = await ERC20Utils.methods.symbol(address).call();
      setSymbol(_symbol);
    } catch {}
  }, [ERC20Utils.methods, address]);

  useEffect(() => {
    getSymbol();
  }, [getSymbol]);

  return (
    <div className={styles.container}>
      <PoolContextProvider address={address}>
        <Head>
          <title>Mimic Finance | Multi Farming Yields Aggerator System</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container maxW="container.xl" mt={10}>
          <>
            <Grid templateColumns="repeat(10, 1fr)" gap={6}>
              <GridItem colSpan={1}>
                <Box>
                  <Image
                    src={getImage(address)}
                    alt={address}
                    width={75}
                    minWidth={45}
                    fallbackSrc="/assets/images/logo-box.png"
                  />
                </Box>
              </GridItem>
              <GridItem colSpan={5}>
                <Text fontSize={{ base: "2xl", md: "3xl", lg: "4xl" }}>
                  <b>{symbol}</b>
                </Text>
              </GridItem>
              <GridItem colSpan={4} style={{ textAlign: "right" }}>
                <ButtonGroup variant="ghost" color="gray.600">
                  <IconButton
                    aria-label="Calculator"
                    icon={<FaCalculator fontSize="15px" />}
                  />
                </ButtonGroup>
                &nbsp; APY
                <Text fontSize={{ base: "2xl", md: "3xl", lg: "4xl" }}>
                  {info.apy} %
                </Text>
              </GridItem>
            </Grid>

            <div className="row">
              <div className="col-md-7" style={{ paddingTop: "20px" }}>
                <Text fontSize="lg">
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  {info.info}
                </Text>
                <br />
                <TVD tokenAddress={address} symbol={symbol}></TVD>
              </div>
              <div className="col-md-5" style={{ paddingTop: "20px" }}>
                <Panel symbol={symbol} tokenAddress={address} />
              </div>
            </div>
          </>
        </Container>
      </PoolContextProvider>
    </div>
  );
};

export default StableCoinAutoCompound;

