import { useEffect, useState, useCallback } from "react";

import styles from "styles/Home.module.css";
import Head from "next/head";
import OpenPool from "constants/OpenPool.json";
import { PoolContextProvider } from "contexts/PoolContext";
import { Panel } from "components/StableCoinPool/Panel";
import { useERC20Utils } from "hooks/useContracts";
import { useRouter } from "next/router";

import {
  Text,
  Grid,
  Container,
  Box,
  GridItem,
  Image,
  IconButton,
  ButtonGroup,
} from "@chakra-ui/react";

import { FaCalculator } from "react-icons/fa";
import TVD from "components/StableCoinPool/TVD";

const StableCoinPool = () => {
  const router = useRouter();
  const { address } = router.query;
  const ERC20Utils = useERC20Utils();
  const [symbol, setSymbol] = useState();
  const info = OpenPool.find((pool) => pool.address == address);

  const getImage = (address) => {
    return `https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/${address}/logo.png`;
  };

  const getSymbol = useCallback(async () => {
    try {
      const _symbol = await ERC20Utils.methods.symbol(address).call();
      setSymbol(_symbol);
    } catch {}
  }, [ERC20Utils.methods, address]);

  useEffect(() => {
    getSymbol();
  }, [getSymbol]);

  return (
    <div className={styles.container}>
      <PoolContextProvider address={address}>
        <Head>
          <title>Mimic Finance | Multi Farming Yields Aggerator System</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container maxW="container.xl" mt={10}>
          <>
            <Grid templateColumns="repeat(10, 1fr)" gap={6}>
              <GridItem colSpan={1}>
                <Box>
                  <Image
                    src={getImage(address)}
                    alt={address}
                    width={75}
                    minWidth={45}
                    fallbackSrc="/assets/images/logo-box.png"
                  />
                </Box>
              </GridItem>
              <GridItem colSpan={5}>
                <Text fontSize={{ base: "2xl", md: "3xl", lg: "4xl" }}>
                  <b>{symbol}</b>
                </Text>
              </GridItem>
              <GridItem colSpan={4} style={{ textAlign: "right" }}>
                <ButtonGroup variant="ghost" color="gray.600">
                  <IconButton
                    aria-label="Calculator"
                    icon={<FaCalculator fontSize="15px" />}
                  />
                </ButtonGroup>
                &nbsp; APR
                <Text fontSize={{ base: "2xl", md: "3xl", lg: "4xl" }}>
                  {info.apr} %
                </Text>
              </GridItem>
            </Grid>

            <Box className="row">
              <Box className="col-md-7" pt={{ base: 5, md: 3, lg: 3 }}>
                <Text
                  fontSize="md"
                  style={{ textAlign: "justify", textJustify: "inter-word" }}
                  pr={{ base: 0, md: 0, lg: 7 }}
                  pl={{ base: 0, md: 0, lg: 7 }}
                >
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  {info.info}
                </Text>
                <br />
                <Box
                  pl={{ base: 0, md: 0, lg: 10 }}
                  pt={{ base: 3, md: 0, lg: 0 }}
                  pb={{ base: 5, md: 0, lg: 0 }}
                  textAlign={{ base: "center", md: "left", lg: "left" }}
                >
                  <TVD tokenAddress={address} symbol={symbol}></TVD>
                </Box>
              </Box>
              <Box className="col-md-5" style={{ paddingTop: "10px" }}>
                <Panel symbol={symbol} tokenAddress={address} />
              </Box>
            </Box>
          </>
        </Container>
      </PoolContextProvider>
    </div>
  );
};

export default StableCoinPool;
