import Head from "next/head";
import styles from "styles/Home.module.css";
import { Text, Box, Container, SimpleGrid } from "@chakra-ui/react";
import Link from "next/link";
import OpenPool from "constants/OpenPool.json";
import { Pool } from "components/Pools/Pool";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mimic Finance | Multi Farming Yields Aggerator System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text fontSize="5xl" fontWeight="bold" pt={7} align="center">
        Enter any Vault with any Token
      </Text>
      <Text fontSize="2xl" align="center" pt={4}>
        Deposit with whitelisted Token{" "}
        <a href="#">
          <Link href="/whitelisted" passHref style={{ color: "teal" }}>
            <small>
              <u>Check here</u>
            </small>
          </Link>
        </a>
      </Text>

      <Container maxW="container.lg">
        <Text fontWeight="bold" fontSize="xl" pt={20}>
          Available Farming Pools
        </Text>

        <SimpleGrid mt={10} minChildWidth='300px' gap={10} spacing='60px'>
          {OpenPool.map((pool) => {
            return (
              <>
                <Box m={2}>
                  <Pool
                    key={pool.address}
                    address={pool.address}
                    poolName={pool.symbol}
                    description={pool.description}
                    token={pool.token}
                    apr={pool.apr}
                    label={pool.symbol}
                    color={pool.color}
                  />
                </Box>
              </>
            );
          })}
        </SimpleGrid>
      </Container>
    </div>
  );
};

export default Home;
