import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Web3 from "web3";
import { useRouter } from "next/router";

import {
  Text,
  Grid,
  Container,
  Box,
  GridItem,
  Image,
  Spinner,
  Center,
  IconButton,
  ButtonGroup,
  Divider,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { FaCalculator } from "react-icons/fa";
import CountUp from "react-countup";

import { Panel } from "../../components/FarmV1/Panel";

const FarmV1 = () => {
  const info = {
    poolName: "",
    label: "",
    description: "",
    tvd: 100,
    apy: 100,
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Mimic Finance | Multi Farming Yields Aggerator System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl" mt={10}>
        <>
          <Grid templateColumns="repeat(10, 1fr)" gap={6}>
            <GridItem colSpan={1}>
              <Box>
                <Image
                  src={"/assets/images/pools/defi-friend.png"}
                  alt="defi-friends"
                  width={150}
                />
              </Box>
            </GridItem>
            <GridItem colSpan={7}>
              <Text fontSize="4xl">
                <b>Farm V1</b>
              </Text>
            </GridItem>
            <GridItem colSpan={2} style={{ textAlign: "right" }}>
              <ButtonGroup variant="ghost" color="gray.600">
                <IconButton
                  aria-label="Calculator"
                  icon={<FaCalculator fontSize="15px" />}
                />
              </ButtonGroup>
              &nbsp; APY
              <Text fontSize="4xl">50 %</Text>
            </GridItem>
          </Grid>

          <Grid templateColumns="repeat(10, 1fr)" gap={10} mt={7}>
            <GridItem colSpan={6}>
              <Text fontSize="xl">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Lorem ipsum
                dolor sit amet, consectetur adipiscing elit. Donec ligula ante,
                commodo et arcu ac, mollis pretium eros. Nunc ornare ut eros eu
                tempus. Maecenas aliquet malesuada convallis. In vel lacus sed
                tellus ullamcorper mattis id id neque. Curabitur elit sem,
                cursus sed mollis et, lobortis ac ex.
              </Text>

              <Box mt={10}>
                <Text fontSize="xl">
                  <b>Total Value Deposited</b>
                </Text>
                <Text fontSize="5xl">
                  $ <CountUp duration={2} end={1244354} separator="," />
                </Text>
              </Box>
            </GridItem>
            <GridItem colSpan={4}>
              <Panel info={info} />
              <Box mt={5}>
                <Text fontSize="xl">
                  <b>Portfolio</b>
                </Text>
                <Box mt={2} p={4} className="portfolio-box">
                  <Grid templateColumns="repeat(9, 1fr)" gap={6}>
                    <GridItem colSpan={3}>
                      <Text fontSize="l">Balance</Text>
                      <Text mt={2} fontSize="m">
                        $ 753.23
                      </Text>
                    </GridItem>
                    <GridItem colSpan={3}>
                      <Text fontSize="l">Reward</Text>
                      <Text mt={2} fontSize="m">
                        $ 5.23
                      </Text>
                    </GridItem>
                    <GridItem colSpan={3}>
                      <Text fontSize="l">Totals</Text>
                      <Text mt={2} fontSize="m">
                        $ 758.46
                      </Text>
                    </GridItem>
                  </Grid>
                </Box>
              </Box>
            </GridItem>
          </Grid>
        </>
      </Container>
    </div>
  );
};

export default FarmV1;
