
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Text, Container, Box, Grid, GridItem, Button } from "@chakra-ui/react";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mimic Finance | Multi Farming Yields Aggerator System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text fontSize="4xl">Documentation</Text>
    </div>
  );
};

export default Home;
