import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Text, Grid, Container, Button } from "@chakra-ui/react";

import { Pool } from "../components/Pools/Pool";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mimic Finance | Multi Farming Yields Aggerator System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text fontSize="5xl" fontWeight="bold" pt={7} align="center">
        Enter any Vault with any Token
      </Text>
      <Text fontSize="2xl" align="center" pt={4}>
        Deposit with Top 10 Market Cap
      </Text>
      <Text align="center" pt={2} style={{ color: "#999" }}>
        BTC, ETH, BNB, ADA, DOT, DOGE, AVAX, LTC, UNI, CAKE AND ALL STABLE COINS{" "}
      </Text>

      <Container maxW="container.lg">
        <Text fontWeight="bold" fontSize="xl" pt={20}>
          Available Pools
        </Text>

        <Grid templateColumns="repeat(1, 1fr)" gap={20} pt={5}>
          <Pool
            poolName="JUSD Pool"
            description="Jack USD Token in CPE World"
            token="Token: JUSD"
            apy={122.32}
            label="JUSD"
            color="#98dfe7"
          />

          {/* <Pool
            poolName="Meme Master"
            description="Only Doge & Shiba lovers"
            token="DOGE - SHIB"
            apy={1553.43}
            label="meme-master"
            color="#FD675C"
          /> */}
        </Grid>
        {/* <Grid templateColumns="repeat(1, 1fr)" gap={20} pt={20}>
          <Pool
            poolName="Happy Three Friends"
            description=" Bitcoin , Ethereum , BNB"
            token="wBTC - wETH - BNB"
            apy={24.98}
            label="happy-three-friend"
            color="#84CBFF"
          />
        </Grid> */}
      </Container>
    </div>
  );
};

export default Home;
